apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: flink-fms
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: flink-fms
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'